// Code generated by neurogonesis. DO NOT EDIT.
// This file was generated at:
// Wed, 02 Sep 2020 03:10:46 +0200

package database

import (
	"strconv"
	"time"

	"github.com/neuronlabs/neuron/errors"
	"github.com/neuronlabs/neuron/mapping"
)

// Neuron_Models stores all generated models in this package.
var Neuron_Models = []mapping.Model{
	&SoftDeletableNoHooks{},
	&TestModel{},
	&Updateable{},
}

// Compile time check if SoftDeletableNoHooks implements mapping.Model interface.
var _ mapping.Model = &SoftDeletableNoHooks{}

// NeuronCollectionName implements mapping.Model interface method.
// Returns the name of the collection for the 'SoftDeletableNoHooks'.
func (s *SoftDeletableNoHooks) NeuronCollectionName() string {
	return "soft_deletable_no_hooks"
}

// IsPrimaryKeyZero implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) IsPrimaryKeyZero() bool {
	return s.ID == 0
}

// GetPrimaryKeyValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) GetPrimaryKeyValue() interface{} {
	return s.ID
}

// GetPrimaryKeyStringValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) GetPrimaryKeyStringValue() (string, error) {
	return strconv.FormatInt(int64(s.ID), 10), nil
}

// GetPrimaryKeyAddress implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) GetPrimaryKeyAddress() interface{} {
	return &s.ID
}

// GetPrimaryKeyHashableValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) GetPrimaryKeyHashableValue() interface{} {
	return s.ID
}

// GetPrimaryKeyZeroValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) GetPrimaryKeyZeroValue() interface{} {
	return 0
}

// SetPrimaryKey implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) SetPrimaryKeyValue(value interface{}) error {
	if _v, ok := value.(int); ok {
		s.ID = _v
		return nil
	}
	// Check alternate types for given field.
	switch _valueType := value.(type) {
	case int8:
		s.ID = int(_valueType)
	case int16:
		s.ID = int(_valueType)
	case int32:
		s.ID = int(_valueType)
	case int64:
		s.ID = int(_valueType)
	case uint:
		s.ID = int(_valueType)
	case uint8:
		s.ID = int(_valueType)
	case uint16:
		s.ID = int(_valueType)
	case uint32:
		s.ID = int(_valueType)
	case uint64:
		s.ID = int(_valueType)
	case float32:
		s.ID = int(_valueType)
	case float64:
		s.ID = int(_valueType)
	default:
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid value: '%T' for the primary field for model: 'SoftDeletableNoHooks'", value)
	}
	return nil
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) SetPrimaryKeyStringValue(value string) error {
	tmp, err := strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	if err != nil {
		return err
	}
	s.ID = int(tmp)
	return nil
}

// SetFrom implements FromSetter interface.
func (s *SoftDeletableNoHooks) SetFrom(model mapping.Model) error {
	if model == nil {
		return errors.Wrap(mapping.ErrNilModel, "provided nil model to set from")
	}
	from, ok := model.(*SoftDeletableNoHooks)
	if !ok {
		return errors.WrapDetf(mapping.ErrModelNotMatch, "provided model doesn't match the input: %T", model)
	}
	*s = *from
	return nil
}

// StructFieldValues gets the value for specified 'field'.
func (s *SoftDeletableNoHooks) StructFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return s.ID, nil
	case 1: // DeletedAt
		return s.DeletedAt, nil
	case 2: // Integer
		return s.Integer, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: SoftDeletableNoHooks'", field.Name())
	}
}

// Compile time check if SoftDeletableNoHooks implements mapping.Fielder interface.
var _ mapping.Fielder = &SoftDeletableNoHooks{}

// GetFieldsAddress gets the address of provided 'field'.
func (s *SoftDeletableNoHooks) GetFieldsAddress(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return &s.ID, nil
	case 1: // DeletedAt
		return &s.DeletedAt, nil
	case 2: // Integer
		return &s.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: SoftDeletableNoHooks'", field.Name())
}

// GetFieldZeroValue implements mapping.Fielder interface.s
func (s *SoftDeletableNoHooks) GetFieldZeroValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return 0, nil
	case 1: // DeletedAt
		return nil, nil
	case 2: // Integer
		return 0, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
}

// IsFieldZero implements mapping.Fielder interface.
func (s *SoftDeletableNoHooks) IsFieldZero(field *mapping.StructField) (bool, error) {
	switch field.Index[0] {
	case 0: // ID
		return s.ID == 0, nil
	case 1: // DeletedAt
		return s.DeletedAt == nil, nil
	case 2: // Integer
		return s.Integer == 0, nil
	}
	return false, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
}

// SetFieldZeroValue implements mapping.Fielder interface.s
func (s *SoftDeletableNoHooks) SetFieldZeroValue(field *mapping.StructField) error {
	switch field.Index[0] {
	case 0: // ID
		s.ID = 0
	case 1: // DeletedAt
		s.DeletedAt = nil
	case 2: // Integer
		s.Integer = 0
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
	return nil
}

// GetHashableFieldValue implements mapping.Fielder interface.
func (s *SoftDeletableNoHooks) GetHashableFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return s.ID, nil
	case 1: // DeletedAt
		if s.DeletedAt == nil {
			return nil, nil
		}
		return *s.DeletedAt, nil
	case 2: // Integer
		return s.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: 'SoftDeletableNoHooks'", field.Name())
}

// GetFieldValue implements mapping.Fielder interface.
func (s *SoftDeletableNoHooks) GetFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return s.ID, nil
	case 1: // DeletedAt
		return s.DeletedAt, nil
	case 2: // Integer
		return s.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: SoftDeletableNoHooks'", field.Name())
}

// SetFieldValue implements mapping.Fielder interface.
func (s *SoftDeletableNoHooks) SetFieldValue(field *mapping.StructField, value interface{}) (err error) {
	switch field.Index[0] {
	case 0: // ID
		if _v, ok := value.(int); ok {
			s.ID = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			s.ID = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			s.ID = int(_v)
		case int16:
			s.ID = int(_v)
		case int32:
			s.ID = int(_v)
		case int64:
			s.ID = int(_v)
		case uint:
			s.ID = int(_v)
		case uint8:
			s.ID = int(_v)
		case uint16:
			s.ID = int(_v)
		case uint32:
			s.ID = int(_v)
		case uint64:
			s.ID = int(_v)
		case float32:
			s.ID = int(_v)
		case float64:
			s.ID = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	case 1: // DeletedAt
		if value == nil {
			s.DeletedAt = nil
			return nil
		}
		if _v, ok := value.(*time.Time); ok {
			s.DeletedAt = _v
			return nil
		}
		// Check if it is non-pointer value.
		if _v, ok := value.(time.Time); ok {
			s.DeletedAt = &_v
			return nil
		}

		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 2: // Integer
		if _v, ok := value.(int); ok {
			s.Integer = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			s.Integer = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			s.Integer = int(_v)
		case int16:
			s.Integer = int(_v)
		case int32:
			s.Integer = int(_v)
		case int64:
			s.Integer = int(_v)
		case uint:
			s.Integer = int(_v)
		case uint8:
			s.Integer = int(_v)
		case uint16:
			s.Integer = int(_v)
		case uint32:
			s.Integer = int(_v)
		case uint64:
			s.Integer = int(_v)
		case float32:
			s.Integer = int(_v)
		case float64:
			s.Integer = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for the model: 'SoftDeletableNoHooks'", field.Name())
	}
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (s *SoftDeletableNoHooks) ParseFieldsStringValue(field *mapping.StructField, value string) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	case 1: // DeletedAt
		var base time.Time
		temp := &base
		if err := temp.UnmarshalText([]byte(value)); err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'DeletedAt' value: '%v' to parse string. Err: %v", s.DeletedAt, err)
		}
		bt, err := temp.MarshalText()
		if err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'DeletedAt' value: '%v' to parse string. Err: %v", s.DeletedAt, err)
		}

		return string(bt), nil
	case 2: // Integer
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: SoftDeletableNoHooks'", field.Name())
}

// Compile time check if TestModel implements mapping.Model interface.
var _ mapping.Model = &TestModel{}

// NeuronCollectionName implements mapping.Model interface method.
// Returns the name of the collection for the 'TestModel'.
func (t *TestModel) NeuronCollectionName() string {
	return "test_models"
}

// IsPrimaryKeyZero implements mapping.Model interface method.
func (t *TestModel) IsPrimaryKeyZero() bool {
	return t.ID == 0
}

// GetPrimaryKeyValue implements mapping.Model interface method.
func (t *TestModel) GetPrimaryKeyValue() interface{} {
	return t.ID
}

// GetPrimaryKeyStringValue implements mapping.Model interface method.
func (t *TestModel) GetPrimaryKeyStringValue() (string, error) {
	return strconv.FormatInt(int64(t.ID), 10), nil
}

// GetPrimaryKeyAddress implements mapping.Model interface method.
func (t *TestModel) GetPrimaryKeyAddress() interface{} {
	return &t.ID
}

// GetPrimaryKeyHashableValue implements mapping.Model interface method.
func (t *TestModel) GetPrimaryKeyHashableValue() interface{} {
	return t.ID
}

// GetPrimaryKeyZeroValue implements mapping.Model interface method.
func (t *TestModel) GetPrimaryKeyZeroValue() interface{} {
	return 0
}

// SetPrimaryKey implements mapping.Model interface method.
func (t *TestModel) SetPrimaryKeyValue(value interface{}) error {
	if _v, ok := value.(int); ok {
		t.ID = _v
		return nil
	}
	// Check alternate types for given field.
	switch _valueType := value.(type) {
	case int8:
		t.ID = int(_valueType)
	case int16:
		t.ID = int(_valueType)
	case int32:
		t.ID = int(_valueType)
	case int64:
		t.ID = int(_valueType)
	case uint:
		t.ID = int(_valueType)
	case uint8:
		t.ID = int(_valueType)
	case uint16:
		t.ID = int(_valueType)
	case uint32:
		t.ID = int(_valueType)
	case uint64:
		t.ID = int(_valueType)
	case float32:
		t.ID = int(_valueType)
	case float64:
		t.ID = int(_valueType)
	default:
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid value: '%T' for the primary field for model: 'TestModel'", value)
	}
	return nil
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (t *TestModel) SetPrimaryKeyStringValue(value string) error {
	tmp, err := strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	if err != nil {
		return err
	}
	t.ID = int(tmp)
	return nil
}

// SetFrom implements FromSetter interface.
func (t *TestModel) SetFrom(model mapping.Model) error {
	if model == nil {
		return errors.Wrap(mapping.ErrNilModel, "provided nil model to set from")
	}
	from, ok := model.(*TestModel)
	if !ok {
		return errors.WrapDetf(mapping.ErrModelNotMatch, "provided model doesn't match the input: %T", model)
	}
	*t = *from
	return nil
}

// StructFieldValues gets the value for specified 'field'.
func (t *TestModel) StructFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return t.ID, nil
	case 1: // CreatedAt
		return t.CreatedAt, nil
	case 2: // UpdatedAt
		return t.UpdatedAt, nil
	case 3: // DeletedAt
		return t.DeletedAt, nil
	case 4: // FieldSetBefore
		return t.FieldSetBefore, nil
	case 5: // FieldSetAfter
		return t.FieldSetAfter, nil
	case 6: // Integer
		return t.Integer, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: TestModel'", field.Name())
	}
}

// Compile time check if TestModel implements mapping.Fielder interface.
var _ mapping.Fielder = &TestModel{}

// GetFieldsAddress gets the address of provided 'field'.
func (t *TestModel) GetFieldsAddress(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return &t.ID, nil
	case 1: // CreatedAt
		return &t.CreatedAt, nil
	case 2: // UpdatedAt
		return &t.UpdatedAt, nil
	case 3: // DeletedAt
		return &t.DeletedAt, nil
	case 4: // FieldSetBefore
		return &t.FieldSetBefore, nil
	case 5: // FieldSetAfter
		return &t.FieldSetAfter, nil
	case 6: // Integer
		return &t.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: TestModel'", field.Name())
}

// GetFieldZeroValue implements mapping.Fielder interface.s
func (t *TestModel) GetFieldZeroValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return 0, nil
	case 1: // CreatedAt
		return time.Time{}, nil
	case 2: // UpdatedAt
		return time.Time{}, nil
	case 3: // DeletedAt
		return nil, nil
	case 4: // FieldSetBefore
		return "", nil
	case 5: // FieldSetAfter
		return "", nil
	case 6: // Integer
		return 0, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
}

// IsFieldZero implements mapping.Fielder interface.
func (t *TestModel) IsFieldZero(field *mapping.StructField) (bool, error) {
	switch field.Index[0] {
	case 0: // ID
		return t.ID == 0, nil
	case 1: // CreatedAt
		return t.CreatedAt == time.Time{}, nil
	case 2: // UpdatedAt
		return t.UpdatedAt == time.Time{}, nil
	case 3: // DeletedAt
		return t.DeletedAt == nil, nil
	case 4: // FieldSetBefore
		return t.FieldSetBefore == "", nil
	case 5: // FieldSetAfter
		return t.FieldSetAfter == "", nil
	case 6: // Integer
		return t.Integer == 0, nil
	}
	return false, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
}

// SetFieldZeroValue implements mapping.Fielder interface.s
func (t *TestModel) SetFieldZeroValue(field *mapping.StructField) error {
	switch field.Index[0] {
	case 0: // ID
		t.ID = 0
	case 1: // CreatedAt
		t.CreatedAt = time.Time{}
	case 2: // UpdatedAt
		t.UpdatedAt = time.Time{}
	case 3: // DeletedAt
		t.DeletedAt = nil
	case 4: // FieldSetBefore
		t.FieldSetBefore = ""
	case 5: // FieldSetAfter
		t.FieldSetAfter = ""
	case 6: // Integer
		t.Integer = 0
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
	return nil
}

// GetHashableFieldValue implements mapping.Fielder interface.
func (t *TestModel) GetHashableFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return t.ID, nil
	case 1: // CreatedAt
		return t.CreatedAt, nil
	case 2: // UpdatedAt
		return t.UpdatedAt, nil
	case 3: // DeletedAt
		if t.DeletedAt == nil {
			return nil, nil
		}
		return *t.DeletedAt, nil
	case 4: // FieldSetBefore
		return t.FieldSetBefore, nil
	case 5: // FieldSetAfter
		return t.FieldSetAfter, nil
	case 6: // Integer
		return t.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: 'TestModel'", field.Name())
}

// GetFieldValue implements mapping.Fielder interface.
func (t *TestModel) GetFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return t.ID, nil
	case 1: // CreatedAt
		return t.CreatedAt, nil
	case 2: // UpdatedAt
		return t.UpdatedAt, nil
	case 3: // DeletedAt
		return t.DeletedAt, nil
	case 4: // FieldSetBefore
		return t.FieldSetBefore, nil
	case 5: // FieldSetAfter
		return t.FieldSetAfter, nil
	case 6: // Integer
		return t.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: TestModel'", field.Name())
}

// SetFieldValue implements mapping.Fielder interface.
func (t *TestModel) SetFieldValue(field *mapping.StructField, value interface{}) (err error) {
	switch field.Index[0] {
	case 0: // ID
		if _v, ok := value.(int); ok {
			t.ID = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.ID = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			t.ID = int(_v)
		case int16:
			t.ID = int(_v)
		case int32:
			t.ID = int(_v)
		case int64:
			t.ID = int(_v)
		case uint:
			t.ID = int(_v)
		case uint8:
			t.ID = int(_v)
		case uint16:
			t.ID = int(_v)
		case uint32:
			t.ID = int(_v)
		case uint64:
			t.ID = int(_v)
		case float32:
			t.ID = int(_v)
		case float64:
			t.ID = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	case 1: // CreatedAt
		if _v, ok := value.(time.Time); ok {
			t.CreatedAt = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.CreatedAt = time.Time{}
			return nil
		}

		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 2: // UpdatedAt
		if _v, ok := value.(time.Time); ok {
			t.UpdatedAt = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.UpdatedAt = time.Time{}
			return nil
		}

		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 3: // DeletedAt
		if value == nil {
			t.DeletedAt = nil
			return nil
		}
		if _v, ok := value.(*time.Time); ok {
			t.DeletedAt = _v
			return nil
		}
		// Check if it is non-pointer value.
		if _v, ok := value.(time.Time); ok {
			t.DeletedAt = &_v
			return nil
		}

		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 4: // FieldSetBefore
		if _v, ok := value.(string); ok {
			t.FieldSetBefore = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.FieldSetBefore = ""
			return nil
		}

		// Check alternate types for the FieldSetBefore.
		if _v, ok := value.([]byte); ok {
			t.FieldSetBefore = string(_v)
			return nil
		}
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 5: // FieldSetAfter
		if _v, ok := value.(string); ok {
			t.FieldSetAfter = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.FieldSetAfter = ""
			return nil
		}

		// Check alternate types for the FieldSetAfter.
		if _v, ok := value.([]byte); ok {
			t.FieldSetAfter = string(_v)
			return nil
		}
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 6: // Integer
		if _v, ok := value.(int); ok {
			t.Integer = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			t.Integer = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			t.Integer = int(_v)
		case int16:
			t.Integer = int(_v)
		case int32:
			t.Integer = int(_v)
		case int64:
			t.Integer = int(_v)
		case uint:
			t.Integer = int(_v)
		case uint8:
			t.Integer = int(_v)
		case uint16:
			t.Integer = int(_v)
		case uint32:
			t.Integer = int(_v)
		case uint64:
			t.Integer = int(_v)
		case float32:
			t.Integer = int(_v)
		case float64:
			t.Integer = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for the model: 'TestModel'", field.Name())
	}
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (t *TestModel) ParseFieldsStringValue(field *mapping.StructField, value string) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	case 1: // CreatedAt
		temp := t.CreatedAt
		if err := t.CreatedAt.UnmarshalText([]byte(value)); err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'CreatedAt' value: '%v' to parse string. Err: %v", t.CreatedAt, err)
		}
		bt, err := t.CreatedAt.MarshalText()
		if err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'CreatedAt' value: '%v' to parse string. Err: %v", t.CreatedAt, err)
		}
		t.CreatedAt = temp
		return string(bt), nil
	case 2: // UpdatedAt
		temp := t.UpdatedAt
		if err := t.UpdatedAt.UnmarshalText([]byte(value)); err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'UpdatedAt' value: '%v' to parse string. Err: %v", t.UpdatedAt, err)
		}
		bt, err := t.UpdatedAt.MarshalText()
		if err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'UpdatedAt' value: '%v' to parse string. Err: %v", t.UpdatedAt, err)
		}
		t.UpdatedAt = temp
		return string(bt), nil
	case 3: // DeletedAt
		var base time.Time
		temp := &base
		if err := temp.UnmarshalText([]byte(value)); err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'DeletedAt' value: '%v' to parse string. Err: %v", t.DeletedAt, err)
		}
		bt, err := temp.MarshalText()
		if err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'DeletedAt' value: '%v' to parse string. Err: %v", t.DeletedAt, err)
		}

		return string(bt), nil
	case 4: // FieldSetBefore
		return value, nil
	case 5: // FieldSetAfter
		return value, nil
	case 6: // Integer
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: TestModel'", field.Name())
}

// Compile time check if Updateable implements mapping.Model interface.
var _ mapping.Model = &Updateable{}

// NeuronCollectionName implements mapping.Model interface method.
// Returns the name of the collection for the 'Updateable'.
func (u *Updateable) NeuronCollectionName() string {
	return "updateables"
}

// IsPrimaryKeyZero implements mapping.Model interface method.
func (u *Updateable) IsPrimaryKeyZero() bool {
	return u.ID == 0
}

// GetPrimaryKeyValue implements mapping.Model interface method.
func (u *Updateable) GetPrimaryKeyValue() interface{} {
	return u.ID
}

// GetPrimaryKeyStringValue implements mapping.Model interface method.
func (u *Updateable) GetPrimaryKeyStringValue() (string, error) {
	return strconv.FormatInt(int64(u.ID), 10), nil
}

// GetPrimaryKeyAddress implements mapping.Model interface method.
func (u *Updateable) GetPrimaryKeyAddress() interface{} {
	return &u.ID
}

// GetPrimaryKeyHashableValue implements mapping.Model interface method.
func (u *Updateable) GetPrimaryKeyHashableValue() interface{} {
	return u.ID
}

// GetPrimaryKeyZeroValue implements mapping.Model interface method.
func (u *Updateable) GetPrimaryKeyZeroValue() interface{} {
	return 0
}

// SetPrimaryKey implements mapping.Model interface method.
func (u *Updateable) SetPrimaryKeyValue(value interface{}) error {
	if _v, ok := value.(int); ok {
		u.ID = _v
		return nil
	}
	// Check alternate types for given field.
	switch _valueType := value.(type) {
	case int8:
		u.ID = int(_valueType)
	case int16:
		u.ID = int(_valueType)
	case int32:
		u.ID = int(_valueType)
	case int64:
		u.ID = int(_valueType)
	case uint:
		u.ID = int(_valueType)
	case uint8:
		u.ID = int(_valueType)
	case uint16:
		u.ID = int(_valueType)
	case uint32:
		u.ID = int(_valueType)
	case uint64:
		u.ID = int(_valueType)
	case float32:
		u.ID = int(_valueType)
	case float64:
		u.ID = int(_valueType)
	default:
		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid value: '%T' for the primary field for model: 'Updateable'", value)
	}
	return nil
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (u *Updateable) SetPrimaryKeyStringValue(value string) error {
	tmp, err := strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	if err != nil {
		return err
	}
	u.ID = int(tmp)
	return nil
}

// SetFrom implements FromSetter interface.
func (u *Updateable) SetFrom(model mapping.Model) error {
	if model == nil {
		return errors.Wrap(mapping.ErrNilModel, "provided nil model to set from")
	}
	from, ok := model.(*Updateable)
	if !ok {
		return errors.WrapDetf(mapping.ErrModelNotMatch, "provided model doesn't match the input: %T", model)
	}
	*u = *from
	return nil
}

// StructFieldValues gets the value for specified 'field'.
func (u *Updateable) StructFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return u.ID, nil
	case 1: // UpdatedAt
		return u.UpdatedAt, nil
	case 2: // Integer
		return u.Integer, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: Updateable'", field.Name())
	}
}

// Compile time check if Updateable implements mapping.Fielder interface.
var _ mapping.Fielder = &Updateable{}

// GetFieldsAddress gets the address of provided 'field'.
func (u *Updateable) GetFieldsAddress(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return &u.ID, nil
	case 1: // UpdatedAt
		return &u.UpdatedAt, nil
	case 2: // Integer
		return &u.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: Updateable'", field.Name())
}

// GetFieldZeroValue implements mapping.Fielder interface.s
func (u *Updateable) GetFieldZeroValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return 0, nil
	case 1: // UpdatedAt
		return time.Time{}, nil
	case 2: // Integer
		return 0, nil
	default:
		return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
}

// IsFieldZero implements mapping.Fielder interface.
func (u *Updateable) IsFieldZero(field *mapping.StructField) (bool, error) {
	switch field.Index[0] {
	case 0: // ID
		return u.ID == 0, nil
	case 1: // UpdatedAt
		return u.UpdatedAt == time.Time{}, nil
	case 2: // Integer
		return u.Integer == 0, nil
	}
	return false, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
}

// SetFieldZeroValue implements mapping.Fielder interface.s
func (u *Updateable) SetFieldZeroValue(field *mapping.StructField) error {
	switch field.Index[0] {
	case 0: // ID
		u.ID = 0
	case 1: // UpdatedAt
		u.UpdatedAt = time.Time{}
	case 2: // Integer
		u.Integer = 0
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field name: '%s'", field.Name())
	}
	return nil
}

// GetHashableFieldValue implements mapping.Fielder interface.
func (u *Updateable) GetHashableFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return u.ID, nil
	case 1: // UpdatedAt
		return u.UpdatedAt, nil
	case 2: // Integer
		return u.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: 'Updateable'", field.Name())
}

// GetFieldValue implements mapping.Fielder interface.
func (u *Updateable) GetFieldValue(field *mapping.StructField) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return u.ID, nil
	case 1: // UpdatedAt
		return u.UpdatedAt, nil
	case 2: // Integer
		return u.Integer, nil
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: Updateable'", field.Name())
}

// SetFieldValue implements mapping.Fielder interface.
func (u *Updateable) SetFieldValue(field *mapping.StructField, value interface{}) (err error) {
	switch field.Index[0] {
	case 0: // ID
		if _v, ok := value.(int); ok {
			u.ID = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			u.ID = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			u.ID = int(_v)
		case int16:
			u.ID = int(_v)
		case int32:
			u.ID = int(_v)
		case int64:
			u.ID = int(_v)
		case uint:
			u.ID = int(_v)
		case uint8:
			u.ID = int(_v)
		case uint16:
			u.ID = int(_v)
		case uint32:
			u.ID = int(_v)
		case uint64:
			u.ID = int(_v)
		case float32:
			u.ID = int(_v)
		case float64:
			u.ID = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	case 1: // UpdatedAt
		if _v, ok := value.(time.Time); ok {
			u.UpdatedAt = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			u.UpdatedAt = time.Time{}
			return nil
		}

		return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
	case 2: // Integer
		if _v, ok := value.(int); ok {
			u.Integer = _v
			return nil
		}
		if field.DatabaseNotNull() && value == nil {
			u.Integer = 0
			return nil
		}

		switch _v := value.(type) {
		case int8:
			u.Integer = int(_v)
		case int16:
			u.Integer = int(_v)
		case int32:
			u.Integer = int(_v)
		case int64:
			u.Integer = int(_v)
		case uint:
			u.Integer = int(_v)
		case uint8:
			u.Integer = int(_v)
		case uint16:
			u.Integer = int(_v)
		case uint32:
			u.Integer = int(_v)
		case uint64:
			u.Integer = int(_v)
		case float32:
			u.Integer = int(_v)
		case float64:
			u.Integer = int(_v)
		default:
			return errors.Wrapf(mapping.ErrFieldValue, "provided invalid field type: '%T' for the field: %s", value, field.Name())
		}
		return nil
	default:
		return errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for the model: 'Updateable'", field.Name())
	}
}

// SetPrimaryKeyStringValue implements mapping.Model interface method.
func (u *Updateable) ParseFieldsStringValue(field *mapping.StructField, value string) (interface{}, error) {
	switch field.Index[0] {
	case 0: // ID
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	case 1: // UpdatedAt
		temp := u.UpdatedAt
		if err := u.UpdatedAt.UnmarshalText([]byte(value)); err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'UpdatedAt' value: '%v' to parse string. Err: %v", u.UpdatedAt, err)
		}
		bt, err := u.UpdatedAt.MarshalText()
		if err != nil {
			return "", errors.Wrapf(mapping.ErrFieldValue, "invalid field 'UpdatedAt' value: '%v' to parse string. Err: %v", u.UpdatedAt, err)
		}
		u.UpdatedAt = temp
		return string(bt), nil
	case 2: // Integer
		return strconv.ParseInt(value, 10, mapping.IntegerBitSize)
	}
	return nil, errors.Wrapf(mapping.ErrInvalidModelField, "provided invalid field: '%s' for given model: Updateable'", field.Name())
}
