// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mapping "github.com/neuronlabs/neuron/mapping"
import mock "github.com/stretchr/testify/mock"
import "github.com/neuronlabs/neuron/repository"

func init() {
	repository.RegisterFactory(&Factory{})
}

// Factory is an autogenerated mock type for the Factory type
type Factory struct {
	mock.Mock
}

// New provides a mock function with given fields: model
func (_m *Factory) New(structer repository.ModelStructer, model *mapping.ModelStruct) (repository.Repository, error) {
	return &Repository{}, nil
}

// RepositoryName provides a mock function with given fields:
func (_m *Factory) RepositoryName() string {
	return "mocks"
}
