// Code generated by neuron-generator. DO NOT EDIT.
// This file was generated at:
// Wed, 13 May 2020 12:22:52 +0200

package tests

type _collectionInitializer func() error

var _collectionInitializers []_collectionInitializer

// Neuron_InitializeCollections collections for provided controller.
func Neuron_InitializeCollections() (err error) {
	for _, initializer := range _collectionInitializers {
		if err = initializer(); err != nil {
			return err
		}
	}
	return nil
}
