// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mapping "github.com/neuronlabs/neuron/mapping"
import mock "github.com/stretchr/testify/mock"
import repositories "github.com/neuronlabs/neuron/repositories"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// New provides a mock function with given fields: model
func (_m *Repository) New(model *mapping.ModelStruct) (repositories.Repository, error) {
	return _m, nil
}

// RepositoryName provides a mock function with given fields:
func (_m *Repository) RepositoryName() string {
	return "mock"
}
